ScoreBoardBundle\Entity\Matchs:
    type: entity
    table: null
    repositoryClass: ScoreBoardBundle\Entity\MatchsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        team1:
            type: string
            length: 255
        team2:
            type: string
            length: 255
        score1:
            type: integer
        score2:
            type: integer
    lifecycleCallbacks: {  }
